Failure mode: no broker package installed
identity-broker-loader HEAD % npm run start:cjs; npm run start:esm

> identity-broker-loader@1.0.0 start:cjs
> node index.cjs

Failed to load native broker plugin
Error: Cannot find module '@azure/identity-broker'
Require stack:
- /home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/msal/nodeFlows/brokerLoader.js
- /home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/msal/nodeFlows/msalPlugins.js
- /home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/plugins/consumer.js
- /home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/index.js
- /home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at tryLoadNativeBrokerPlugin (/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/msal/nodeFlows/brokerLoader.js:10:40)
    at Object.generatePluginConfiguration (/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/msal/nodeFlows/msalPlugins.js:77:82)
    at createMsalClient (/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/msal/nodeFlows/msalClient.js:69:59)
    at new InteractiveBrowserCredential (/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/credentials/interactiveBrowserCredential.js:51:64)
    at main (/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/index.cjs:4:21)
    at Object.<anonymous> (/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/index.cjs:9:1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/msal/nodeFlows/brokerLoader.js',
    '/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/msal/nodeFlows/msalPlugins.js',
    '/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/plugins/consumer.js',
    '/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/index.js',
    '/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/index.cjs'
  ]
}
Error: Error: Broker for WAM was requested to be enabled, but no native broker was configured. You must install the identity-broker plugin package (`npm install --save @azure/identity-broker`) and enable it by importing `useIdentityPlugin` from `@azure/identity` and calling `useIdentityPlugin(createNativeBrokerPlugin())` before using `enableBroker`.
    at Object.generatePluginConfiguration (/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/msal/nodeFlows/msalPlugins.js:82:23)
    at createMsalClient (/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/msal/nodeFlows/msalClient.js:69:59)
    at new InteractiveBrowserCredential (/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/commonjs/credentials/interactiveBrowserCredential.js:51:64)
    at main (/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/index.cjs:4:21)
    at Object.<anonymous> (/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/index.cjs:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)

> identity-broker-loader@1.0.0 start:esm
> node index.mjs

Failed to load native broker plugin
Error: Cannot find module '@azure/identity-broker'
Require stack:
- /home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/esm/msal/nodeFlows/brokerLoader.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at tryLoadNativeBrokerPlugin (file:///home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/esm/msal/nodeFlows/brokerLoader.js:9:40)
    at Object.generatePluginConfiguration (file:///home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/esm/msal/nodeFlows/msalPlugins.js:73:34)
    at createMsalClient (file:///home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/esm/msal/nodeFlows/msalClient.js:64:42)
    at new InteractiveBrowserCredential (file:///home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/esm/credentials/interactiveBrowserCredential.js:48:27)
    at main (file:///home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/index.mjs:4:21)
    at file:///home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/index.mjs:9:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/esm/msal/nodeFlows/brokerLoader.js'
  ]
}
Error: Error: Broker for WAM was requested to be enabled, but no native broker was configured. You must install the identity-broker plugin package (`npm install --save @azure/identity-broker`) and enable it by importing `useIdentityPlugin` from `@azure/identity` and calling `useIdentityPlugin(createNativeBrokerPlugin())` before using `enableBroker`.
    at Object.generatePluginConfiguration (file:///home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/esm/msal/nodeFlows/msalPlugins.js:78:23)
    at createMsalClient (file:///home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/esm/msal/nodeFlows/msalClient.js:64:42)
    at new InteractiveBrowserCredential (file:///home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/node_modules/@azure/identity/dist/esm/credentials/interactiveBrowserCredential.js:48:27)
    at main (file:///home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/index.mjs:4:21)
    at file:///home/maorleger/workspace/azure-sdk-experiments/identity-broker-loader/index.mjs:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:263:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:540:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)